export const modelName = "meta-llama-instruct-3-1-8B";
export const embeddingModelName = "minilm";
export const classificationModelName = "roberta-base";
export const feedbackCollectionName = "feedback";

export const demoFeedback = [
  "The interface is really intuitive and easy to use!",
  "It would be great to have a dark mode option.",
  "I encountered a bug when trying to upload an image.",
  "The loading time is a bit slow on my device.",
  "I love the new feature for sharing projects with my team!",
  "Some tooltips or guides would help explain the features better.",
  "The mobile version doesn’t seem to work properly on my phone.",
  "Adding support for multiple languages would be awesome.",
  "The design is clean and professional-looking!",
  "I wish there were more customization options available.",
  "The notifications feel a bit overwhelming; maybe add an option to customize them.",
  "Search functionality works perfectly—very accurate and fast.",
  "There’s a lot of potential here, but the navigation is a bit clunky.",
  "I would appreciate more integrations with third-party apps.",
  "The onboarding process is smooth and well thought out!",
  "I noticed some typos in the help documentation.",
  "An offline mode would make this app even more useful.",
  "Really love the gamification aspect; it makes it fun to use.",
  "The app crashes when I try to access the settings page.",
  "I think the color scheme could be more visually appealing.",
  "It’s great that you allow image uploads, but it takes too long to process them.",
  "Adding a calendar integration would make this much better.",
  "The team collaboration tools are amazing—keep it up!",
  "I’d love to see an option for exporting data to Excel.",
  "The search bar isn’t very responsive on slower networks.",
  "The AI suggestions are helpful but sometimes feel repetitive.",
  "I found it hard to locate the logout button—it’s not intuitive.",
  "The activity feed provides a lot of useful insights—great addition!",
  "Can you add a feature to customize the dashboard layout?",
  "This is exactly what I needed for my team’s workflow—thank you!",
  "The pricing is a bit high for small teams like ours.",
  "I’d like an option to set reminders or notifications for specific tasks.",
  "The font size is too small for comfortable reading.",
  "The widget integration worked perfectly without any hiccups.",
  "There seems to be a delay in receiving email notifications.",
  "The sentiment analysis feature is surprisingly accurate!",
  "Can you add support for bulk uploads of files?",
  "It would be nice to have a tutorial video to get started quickly.",
  "The weekly reports are very helpful and concise.",
  "I had trouble understanding how to set up the authentication provider.",
  "It would be great if you added support for custom domains.",
  "The layout feels a bit cluttered; consider simplifying it.",
  "I love how lightweight and fast the app feels compared to others.",
  "The live chat support was very responsive and helpful—thank you!",
  "Can you add a feature to undo changes in real time?",
  "The app seems to drain my battery quickly when running in the background.",
  "Having keyboard shortcuts would improve productivity a lot.",
  "The progress tracking is super helpful for keeping me on track.",
  "Some buttons feel unresponsive; they need better feedback.",
];
